ERROR_ELEMENT_PRESENCE_TIMEOUT = 10
ERROR_CANNOT_NAVIGATE_TO_INVALID_URL = 11
EXIT_CODE_FILE_ERROR = 12
EXIT_CODE_CONFIG_READING_ERROR = 13
EXIT_CODE_CONFIG_PARSING_ERROR = 14
EXIT_CODE_LOGGER_NOT_SET_UP = 15
